api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_items_per_page: 20
        pagination_client_items_per_page: true
        page_parameter_name: 'page'

    # Configure what formats are supported by the API
    graphql:
        collection:
            pagination:
                enabled: true
